import pandas as pd
import matplotlib.pyplot as plt
from dotenv import load_dotenv
import os

load_dotenv()

def load_and_plot_results():
    '''Load results from results.csv file generated by YOLOv8 model during training.
        Plot the train and validation losses, and top-1 and top-5 accuracies along the epochs.'''

    results = pd.read_csv(os.environ.get("results_csv_dir"))

    """
    results.columns look like this:

    Index(['                  epoch', '             train/loss',
        '  metrics/accuracy_top1', '  metrics/accuracy_top5',
        '               val/loss', '                 lr/pg0',
        '                 lr/pg1', '                 lr/pg2'],
        dtype='object')
    """

    train_loss = results["             train/loss"]
    val_loss = results["               val/loss"]
    acc_top1 = results["  metrics/accuracy_top1"]
    acc_top5 = results["  metrics/accuracy_top5"]
    epochs = range(len(results["                  epoch"]))

    # Plot loss
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, train_loss, label="training_loss")
    plt.plot(epochs, val_loss, label="val_loss")
    plt.title("Loss")
    plt.xlabel("Epochs")
    plt.legend()

    # Plot accuracy
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, acc_top1, label="Accuracy-Top1")
    plt.plot(epochs, acc_top5, label="Accuracy-Top5")
    plt.title("Accuracy")
    plt.xlabel("Epochs")
    plt.legend()

    plt.imshow(plt.imread(os.environ.get("results_png_dir")))

    plt.show()